### ISSUE TITLE
Make EXECUTE_COMMANDS optional

### ISSUE THREAD

**Issue by jasonkarns** [technote-space/create-pr-action#155]
## Please describe your suggestion: 提案の概要

This actions is almost exactly what I'm looking for. I have a workflows that runs a number of steps. During those steps, some files _may_ become modified (conditionally).

Under some condition, I'd like to use this action to then commit those changes and open a PR. However, the present configuration makes EXECUTE_COMMANDS a required input. Since I have no commands that need executed as part of this action, it's an unnecessary input.

## Describe the solution you'd like: 考えうる解決方法

I'd like to be able to specify a minimal set of arguments to this action:

```yml
steps:
  - run: foo
  - name: Update npm packages
    if: github.event_name == 'schedule'
    uses: technote-space/create-pr-action@v2
    with:
      COMMIT_MESSAGE: update foo
      PR_BRANCH_NAME: update-foo
```

(I'm hoping/assuming that the PR title and PR description are automatically defaulted to the values from the commit just like on GitHub itself?)

## Describe alternatives you've considered: 考えうる代替案
I could provide an empty EXECUTE_COMMANDS, but that's just extra config for no purpose.

**Comment by jasonkarns** [comment]
I'm running the following workflow but the action doesn't create a PR:

```yml
  pr:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run lint:lts -- --fix
    - if: failure()
      uses: technote-space/create-pr-action@v2
      with:
        COMMIT_MESSAGE: 'Include warning message per LTS schedule'
        PR_BRANCH_NAME: lts-warning-message
```

I get the following output, which doesn't indicate a reason for failure. (nor does the action actually "fail" so I have no idea what's missing)

![image](https://user-images.githubusercontent.com/119972/78854590-b93abb00-79ef-11ea-9c52-0e45c6283041.png)


(side-note, lower-case seems to be the convention for action inputs, as opposed to env vars. Are Actions case-sensitive when it comes to inputs?)
