### ISSUE TITLE
Cannot submit pull request to private repo

### ISSUE THREAD

**Issue by steveoh** [technote-space/create-pr-action#240]
## Describe the bug: 

Cannot write to private repository

## To Reproduce: 再現手順

I added a bot account email as a write contributor to the repo. set the name and email to that person, used their personal access token with the full repo scope and set it as a secret for the workflow. It's able to list the pull requests etc but when it goes to write to the repo it fails.

## Expected behavior: 期待する動作

The pull request is submitted

```
[main] command [git push origin bot/provider-update-0:refs/heads/bot/provider-update-0] exited with code 128. message: remote: Write access to repository not granted.
  fatal: unable to access 'https://github.com/my/repo/': The requested URL returned error: 403
```

## Additional context: 補足

```yaml
      - name: 🔧 Update terraform providers
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            ./update-providers.sh
          COMMIT_MESSAGE: "chore: :package: update terraform provider"
          PR_BRANCH_PREFIX: bot/
          PR_BRANCH_NAME: provider-update-${PR_ID}
          PR_TITLE: Provider updates
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}
```
