### ISSUE TITLE
Unclear what is required for auto merge

### ISSUE THREAD

**Issue by mcassaniti** [technote-space/create-pr-action#245]
I've configured the below step in my workflow but I believe I'd probably need another workflow to make the auto merge complete.

```yaml
        - name: Create PR
          uses: technote-space/create-pr-action@v2
          with:
            EXECUTE_COMMANDS: echo -n "${{ steps.ver.outputs.ver }}" > version
            COMMIT_MESSAGE: 'Automatic version bump to ${{ steps.ver.outputs.ver }}'
            PR_TITLE: 'Automatic version bump to ${{ steps.ver.outputs.ver }}'
            PR_BODY: 'Automatic version bump'
            PR_BRANCH_NAME: 'auto-bump-${PR_NUMBER}'
            AUTO_MERGE_THRESHOLD_DAYS: 1
```

The PR is created correctly but it hasn't automatically merged within 24 hours.
